### ISSUE TITLE
为什么精度，召回率等评价指标没有变化呢？

### ISSUE THREAD

**Issue by CUITCHENSIYU** [shanglianlm0525/yolov5_specific_size#2]
为什么精度，召回率等评价指标没有变化呢？在第一次迭代后等到一个结果后后续训练都不再变化了

**Comment by shanglianlm0525** [comment]
你要不要检查下自己的训练数据

**Comment by CUITCHENSIYU** [comment]
数据集应该是没有问题的，因为我在官方开源的项目上训练是正常的。在你的工程目录下有两个训练文件（train_solarcell_test.py 和 train_solarcell.py）。我们是选择哪一个呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shanglianlm0525/yolov5_specific_size"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月18日(星期三) 下午4:51
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2)





 
你要不要检查下自己的训练数据
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shanglianlm0525** [comment]
两个是不同的，bigcut就是原始的yolov5，solarcell是可以指定宽和高的



---Original---
From: ***@***.***&gt;
Sent at: 2021年8月18日(Wed) PM4:54
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2)




 数据集应该是没有问题的，因为我在官方开源的项目上训练是正常的。在你的工程目录下有两个训练文件（train_solarcell_test.py 和 train_solarcell.py）。我们是选择哪一个呢？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "shanglianlm0525/yolov5_specific_size"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年8月18日(星期三) 下午4:51 
 ***@***.***&amp;gt;; 
 ***@***.******@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2) 
 
 
 
 
 
   
 你要不要检查下自己的训练数据 
   
 — 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shanglianlm0525** [comment]
我感觉还是你的数据或者数据处理脚本有问题，这个代码我用了很多不同的数据集，都是可以正常运行的



---Original---
From: ***@***.***&gt;
Sent at: 2021年8月18日(Wed) PM4:54
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2)




 数据集应该是没有问题的，因为我在官方开源的项目上训练是正常的。在你的工程目录下有两个训练文件（train_solarcell_test.py 和 train_solarcell.py）。我们是选择哪一个呢？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "shanglianlm0525/yolov5_specific_size"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年8月18日(星期三) 下午4:51 
 ***@***.***&amp;gt;; 
 ***@***.******@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2) 
 
 
 
 
 
   
 你要不要检查下自己的训练数据 
   
 — 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CUITCHENSIYU** [comment]
我看你的工程里有两个train.py文件，你用的是哪一个呢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月18日(星期三) 晚上7:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2)

**Comment by shanglianlm0525** [comment]
bigcut和solarcell两个都用，不同的方式



---Original---
From: ***@***.***&gt;
Sent at: 2021年8月18日(Wed) Evening7:39
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2)




 我看你的工程里有两个train.py文件，你用的是哪一个呢------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 ***@***.***&amp;gt; 
 发送时间:&amp;nbsp;2021年8月18日(星期三) 晚上7:29 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2) 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CUITCHENSIYU** [comment]
那还有一个solarcell-test是啥------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月18日(星期三) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2)

**Comment by shanglianlm0525** [comment]
测试用的，没用



---Original---
From: ***@***.***&gt;
Sent at: 2021年8月18日(Wed) Evening8:13
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2)




 那还有一个solarcell-test是啥------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 ***@***.***&amp;gt; 
 发送时间:&amp;nbsp;2021年8月18日(星期三) 晚上7:41 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2) 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CUITCHENSIYU** [comment]
好吧，谢谢回复------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月18日(星期三) 晚上8:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shanglianlm0525/yolov5_specific_size] 为什么精度，召回率等评价指标没有变化呢？ (#2)
